### ISSUE TITLE
Packaging

### ISSUE THREAD

**Issue by johannes-kk** [funkyADers/cs207-FinalProject#12]
Packaging and deploying the project.

**Minimum package requirements**
- The software should be available for download from your GitHub organization.
- At this point, there is no need for you to release it on PyPI.
- You should provide a requirements.txt file (or something similar) with your software so other developers are able to install the necessary dependencies.
- After a user installs your package, they should be able to use it without difficulty.

**Comment by zinka88** [comment]
@tyler-yoo94 
I tried the pip install command and I "think" it worked but I also got the error message (see attached). It might not be an issue but I wanted to flag in case. 
<img width="566" alt="funkyAD pip install" src="https://user-images.githubusercontent.com/7987364/68437379-c4fb2a80-018e-11ea-9a41-7bd0f2ac8640.png">

**Comment by zinka88** [comment]
@tyler-yoo94 @FabioPru @johannes-kk 

Current issues with import: 
<img width="911" alt="funkyAD import" src="https://user-images.githubusercontent.com/7987364/68437969-a0a04d80-0190-11ea-8441-a21a77f72466.png">
