### ISSUE TITLE
Handling edge cases in base.py

### ISSUE THREAD

**Issue by zinka88** [funkyADers/cs207-FinalProject#41]
Some errors occurring for edge case tests in test_base.py: 

- need to throw an error for non-function (string) inputs to AD.
- handle constant input to AD by either throwing an error (like for string) or changing it into a function that can be processed.
- can't take a constant function right now. need to address (haven't figure out how to yet).
- need to handle the situation when the user calls grad and thus _evaluate without any arguments.
- need to raise an error when you try to set the seed (in set_seed) to something that isn't an array
- raise type error in Node if strings are passed in.

**Comment by johannes-kk** [comment]
@zinka88 are these still pertinent?

**Comment by zinka88** [comment]
@johannes-kk  no, we can close this. I might find more in this round of testing, but I'll create a new issue if that happens.
