### ISSUE TITLE
Full working forward mode

### ISSUE THREAD

**Issue by johannes-kk** [funkyADers/cs207-FinalProject#54]
**Requirements**
- [ ] Library handles real functions of one or more variables, including the situation where a user might have multiple functions each of multiple variables
- [ ] **Library handles vector functions with multiple real scalar or vector inputs**

**Comment by FabioPru** [comment]
I think all of this is there already no? Can you make an example of what is missing?

**Comment by johannes-kk** [comment]
This issue was part of putting all requirements into Issues. I have not come across anything missing on this front, but kept them unchecked so that others would verify that. I should have been clear on that. Seems like everything's in place.
